version: 2
updates:
    - package-ecosystem: "gradle"
      directory: "/"
      schedule:
          interval: "daily"
      groups:
          gradle-updates:
              patterns:
                  - "*"

    # Ignore Docs Updates hopefully
    - package-ecosystem: "npm"
      directory: "/docs/"
      schedule:
          interval: "weekly"
      ignore:
          - dependency-name: "*"
