version: 2
registries:

    devauth:
        type: maven-repository
        url: https://pkgs.dev.azure.com/djtheredstoner/DevAuth/_packaging/public/maven/v1

    hypixelapi:
        type: maven-repository
        url: https://repo.hypixel.net/repository/Hypixel

    parchmentmc:
        type: maven-repository
        url: https://maven.parchmentmc.org/

    modrinth:
        type: maven-repository
        url: https://api.modrinth.com/maven

    teamresourceful:
        type: maven-repository
        url: https://maven.teamresourceful.com/repository/maven-public/

    nucleoid: # what is the proper name for this?
        type: maven-repository
        url: https://maven.nucleoid.xyz/

    fishstiz:
        type: maven-repository
        url: https://raw.githubusercontent.com/fishstiz/maven/m2

    operationpotato-snapshots:
        type: maven-repository
        url: https://maven.operationpotato.com/snapshots

    operationpotato-releases:
        type: maven-repository
        url: https://maven.operationpotato.com/releases
updates:
    -   package-ecosystem: gradle
        directory: /
        registries: "*"
        schedule:
            interval: daily
        groups:
            gradle-updates:
                patterns:
                    - "*"
