[versions]

minecraft = "1.21.10"
parchment = "2025.10.05"
sbapi-mc-version = "1.21.9"
fabric-api = "0.136.0+1.21.10"

[libraries]

minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
parchment = { module = "org.parchmentmc.data:parchment-1.21.9", version.ref = "parchment" }
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }

